config/routes.rb
Rails.application.routes.draw do
  resources :teams
  resources :users
  resources :events
  get 'sessions/new'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root :to => redirect('/login')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :team
	validates :title, presence: true
	validates :date, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :users
	has_many :events
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :team
	validates :username, presence: true
	validates :team, presence: true
	validates :permission, presence: true

	after_initialize :set_permission

	# def authenticate(provided_password)
	# 	self.password == provided_password
	# end
	def set_permission
		self.permission ||= 2
	end
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_login
  	# check session to see if authenticated
  	# render 404 page and status if not
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :time, :place, :people)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
  	@user = User.find_by(username: params[:session][:username])
  	if @user && @user.authenticate(params[:session][:password])
      session[:id] = @user.id
      session[:permission] = @user.permission
      session[:in] = true
  		redirect_to @user
  	else
  		fail RuntimeError, "implemement failed login"
  	end
  end

  def destroy
    session.delete(:id)
    session.delete(:permission)
    session.delete(:in)
    redirect_to login_path
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @team = Team.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :team_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :event_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, id: :event_time %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, id: :event_place %>
  </div>

  <div class="field">
    <%= form.label :people %>
    <%= form.text_field :people, id: :event_people %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>
<% if session[:permission] <= 1 %>
<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
<% else %>
  <h1>Path Unknown</h1>
  <%= link_to 'Events', events_path %>
<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
<% if session[:permission] <= 1 %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>People</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.people %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Event', new_event_path %>  |
<%= link_to 'People', users_path %>
<% else %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>People</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.date %></td>
        <td><%= event.people %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'People', users_path %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>
<% if session[:permission] <= 1 %>
<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>
<% else %>
  <h1>Path Unknown</h1>
  <%= link_to 'Events', events_path %>
<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>People:</strong>
  <%= @event.people %>
</p>
<% if session[:permission] <= 1 %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FuRyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if session[:in] == true || current_page?(login_path) || current_page?(signup_path) %>
      <%= yield %>
    <% else %>
      <h1>ERROR!</h1>
      <p>You are not signed in!</p>
      <%= link_to "Login", login_path %>
    <% end %>
  </body>
</html>

app/views/users/_form.html.erb
<% if session[:permission] == 0 %>
<div class="loginForm">
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :permission %>
    <%= form.text_field :permission, id: :user_permission %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
<% else %>
<div class="loginForm">
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :team %>
    <%= form.collection_select(:team_id, Team.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<% if session[:id].eql?(@user.id) || session[:permission] == 0 %>
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
<% else %>
  <h1>Path Unknown</h1>
  <%= link_to 'People', users_path %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<% if session[:permission] == 0 %>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.team.name %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %><td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Team</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.team %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br>

<%= link_to 'Events', events_path %>  |
<%= link_to 'Log out', logout_path, method: :delete %>

app/views/users/new.html.erb
<h1 class="header">New User</h1>

<%= render 'form', user: @user %>
<p class="linkExtrude">
<%= link_to 'Back', login_path %>
</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Team:</strong>
  <%= @user.team.name %>
</p>

<p>
  <strong>Permission:</strong>
  <% if @user.permission == 0 %>
    Owner
  <% elsif @user.permission == 1 %>
    Admin
  <% else %>
    Member
  <% end %>
</p>

<% if session[:id].eql?(@user.id) %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Home', events_path %>  |
<%= link_to 'People', users_path %>